name: CI/CD - Deploy Azure Static Web App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web Apps

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2. Build and Deploy
      - name: Build and Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src"            # Caminho para o código da app (ajusta se necessário)
          api_location: ""                 # Caminho para APIs (se não tiveres, deixa vazio)
          output_location: "./src"         # Caminho para ficheiros finais (ajusta se necessário)

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Deployment

    steps:
      - name: Close Pull Request Deployment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"C_WEB_APPS_API_TOKEN_NICE_MOSS_0817F8110 }}
          action: "close"
